### ISSUE TITLE
Fix Flickering when using colorbar

### ISSUE THREAD

**Issue by brendancol** [Quansight/lsst_dashboard#103]
Address bugs and undesirable behavior in dynamic interactive plots, including:
flickering of figures that contain datashaded overlays 
(and related issue of datashaded colorbar requiring using ‘rasterize’, but then not being able to ‘dynspread’), pr by Jim./Jean-Luc
Bokeh toolbar bug that sometimes requires the select/unselect action, and

@jbednar: can you show us where the PR to fix this issue is?
@philippjfr

**Comment by jbednar** [comment]
The above may describe several different issues. The specific fix for using `spread` with `rasterize` is https://github.com/holoviz/datashader/pull/771, which is just a start to the solution, but does demonstrate that spreading is feasible for aggregates rather than pixels, which allows using `rasterize`.
