### ISSUE TITLE
Implement Partitioning with Kartothek

### ISSUE THREAD

**Issue by brendancol** [Quansight/lsst_dashboard#121]
dashboard now works off of KTK datasets
https://github.com/Quansight/lsst_dashboard/pull/137

**Comment by brendancol** [comment]
```
Given Longitude/latitude/zoom to tile numbers :

n = 2 ^ zoom
xtile = n * ((lon_deg + 180) / 360)
ytile = n * (1 - (log(tan(lat_rad) + sec(lat_rad)) / π)) / 2
Note that log() in this pseudo code refers to natural log (often "ln()" in common math syntax, but often "log()" in many programming languages).

Given Tile numbers to longitude/latitude :

n = 2 ^ zoom
lon_deg = xtile / n * 360.0 - 180.0
lat_rad = arctan(sinh(π * (1 - 2 * ytile / n)))
lat_deg = lat_rad * 180.0 / π
```

**Comment by brendancol** [comment]
Approach
---------

1. Use astropy to go from ra / dec to degrees
2. Convert degrees to tile x, y, z
3. convert tile x,y,z to quakey

**Comment by brendancol** [comment]
```
>>> from astropy import units as u
>>> from astropy.coordinates import SkyCoord
>>> c = SkyCoord(ra=10.625*u.degree, dec=41.2*u.degree, frame='icrs')
```

**Comment by brendancol** [comment]
Let's vendor-in https://github.com/n1try/pyquadkey2/tree/master/src/pyquadkey2/quadkey

**Comment by timothydmorton** [comment]
Just got off a call with @dharhas; I think that instead of making our own tilings, our approach should be to use the tract/patch tiling that exists already in the dataset.  Practically, I think we would actually be OK if, for whatever our datashader bounding box is, we only read data from tracts that overlap that box.  We could in principle repeat this down to the patch level also, but patches are small enough that I don't think that will actually be necessary at all.

So I think what we would need to enable this would be just a function that returns the tracts that overlap a given bounding box in ra/dec.  This can be either reverse-enginereed from [this gdf file](https://github.com/Quansight/lsst_dashboard/blob/master/deepCoadd_skyMap.geojson) that defines the tract polygons, or using code from the LSST stack (less ideal for independent development).

**Comment by dharhas** [comment]
Actually maybe we don't need the sub-tract level part. spatialpandas will let us build a hilbert curve as a column in the data. If we use kartothek to partition data and retrieve data at the tract scale and then the dataframe we retrieve for the tract has the hilbert curve distance can holoviews/datashader take advantage  of this information to speed up rendering when zoomed in/panning? 

Essentially the idea would be to:

1. Use spatialpandas to compute the hilbert curve distance ahead of time and add as a column
1.5 Hilbert curve sort/repack?
2. Partition the resulting dataset with kartothek by filter, tract 
3. Retrieve a dask dataframe by filter/tracts (tracts are determined by an ra/dec bbox)
4. Let holoviews/datashader do their magic using the hilbert curve distance 

@jonmmease @philippjfr @brendancol ?

**Comment by jonmmease** [comment]
Unfortunately holoviews and datashader don't do any of the hilbert curve logic, that's all in `spatialpandas`. And really, once packing is completed spatialpandas only looks at the bounding boxes of partitions, not the hilbert curve distances.

Here's the flow for spatialpandas
 - `pack_partitions` generates a hilbert curve distance column for a single geometry column, then sorts and partitions by the column, then compute bounding boxes per partition.
 - `to_parquet` computes bounding boxes per partition (if not already done), and writes these bounding boxes of each `geometry` column as JSON in the `_common_metadata` file.  `to_parquet` doesn't care how the partitions were generated, it only cares about the bounding boxes of the partitions.
 - `pack_partitions_to_parquet` combines both of these operations, sorting and writing partitions to parquet using a custom shuffling algorithm that has better memory usage characteristics than the what we were seeing using Dask's shuffle.
- `read_parquet_dask` loads a parquet dataset written by `to_parquet` or `pack_partitions_to_parquet` into a DaskGeoDataFrame and reads the bounding box metadata per partition so that it doesn't need to be recomputed.

If you already have the dataset partitioned spatially by tracts, then you could skip the `pack_partitions` part and use `to_parquet` to write the parquet file and the bounding box metadata.

But, I don't see yet how this workflow could be easily combined with kartothek as it exists right now.

Here's an approach that I think would work right now using only kartothek.
 - Partition dataset by tracts (or subtracts if you want the partitions to be smaller)
 - For points, store `x` and `y` positions as two columns (For extended objects, store the bounding box of each objects as four columns: `x0`, `x1`, `y0`, `y1`)
 - Save dataset to kartothek, marking both `x` and `y` as secondary index columns (or `x0`, `x1`, `y0`, and `y1` for the case of extended objects). This way I believe kartothek will compute and save the min/max of each secondary index column per partition.
 - Then when loading data with kartothek, filter to particular `x` and `y` intervals (for extended objects, the filter would use `x0`, `x1`, `y0`, and `y1`).

If you still end up with a lot of partitions at this point, it might be worth creating a `spatialpandas` `DaskGeoDataFrame` from the result.  There's no public API for this at the moment, but if there's a way to get the per-partition `x`/`y` ranges from kartothek you could use those to compute bounding boxes and give that info to `spatialpandas` so that it wouldn't compute bounding boxes itself.

**Comment by brendancol** [comment]
https://github.com/Quansight/lsst_dashboard/pull/137
