### ISSUE TITLE
Change SkyPlots To Datashade + Transition to individual points based on zoom level

### ISSUE THREAD

**Issue by dharhas** [Quansight/lsst_dashboard#157]

**Comment by philippjfr** [comment]
Should this be zoom level dependent or dependent on the number of points in the viewport?

**Comment by dharhas** [comment]
@philippjfr What do you think? I would say number of points makes more sense to me. @timothydmorton ?

**Comment by philippjfr** [comment]
Same here I think, only reason to make it zoom level dependent would be to provide more predictable behavior. Counting the number of points should be pretty cheap once persisted.

**Comment by timothydmorton** [comment]
The sky density of sources doesn't change that much from field to field, so zoom level should be approximately the same as number of sources, at least on the sky plots.  The scatter plots is a different story though, since those have a much different density distribution.  I'm OK with either solution, as long as counting points doesn't ding performance.

**Comment by philippjfr** [comment]
This has been done and merged. We can still tweak the thresholds if necessary.
