### ISSUE TITLE
Dashboard Design - Wireframe

### ISSUE THREAD

**Issue by dharhas** [Quansight/lsst_dashboard#23]
Adding wireframes of the two dashboard views. Please comment so we can finalize design.

![lsst_dashboard_skyplot_view](https://user-images.githubusercontent.com/561301/61986126-89b76000-afd2-11e9-9be7-4515dd3c80b5.jpg)
![lsst_dashboard_detail_view](https://user-images.githubusercontent.com/561301/61986130-8f14aa80-afd2-11e9-928a-b560d4189edc.jpg)

**Comment by dharhas** [comment]
- [ ] Forgot to put the good/bad visual indicators on the metric checkboxes.
- [ ] We might need a view that shows all metrics good/bad indicators at the same time for quick status check

**Comment by timothydmorton** [comment]
Thanks, Dharhas.  Looks great; here are some thoughts for now:

* The plot in the "sky view" plot should take up as much real estate as possible, and doesn't need the summary stats table.
* "FILTER WHEN FALSE" etc. might be reworded "SELECT IF FALSE"/"SELECT IF TRUE"?
* I agree that we should have something for quick status check.  One idea might be that the skyplot view just has a color-indicated heatmap (with rows being filters, and names on hover) instead of a checkbox list, and that clicking on the squares would select/deselect in that view (and switching to the detail view would have those same metrics checked, and the 'breadcrumbs' would be the same between the two views). 
* There should indeed be a forced/unforced selector to switch between the forced and unforced coadd tables.
* The plot scroll bar in the detail view should only scroll the scatter/sky plots, not the top line plot; also, there shouldn't need to be a scroll bar in the sky view

**Comment by timothydmorton** [comment]
Regarding the above suggested "forced vs. unforced" selector; I think instead it might turn out to be better to have *both* forced and unforced loaded, and for columns of interest to be drawn from either one or the other.  I'm looking into this in more detail right now, working out exactly a correspondence between the plots that people here have been using and the table columns that produce them.

**Comment by timothydmorton** [comment]
This would have to be specified of course in whatever .yaml specification we're using to define what columns to use.
