### ISSUE TITLE
Add Colorbar to Skyplot

### ISSUE THREAD

**Issue by brendancol** [Quansight/lsst_dashboard#43]

**Comment by chbrandt** [comment]
* https://github.com/pyviz/holoviews/issues/2102

**Comment by philippjfr** [comment]
I'd really just suggest to switch to the rasterize operation. Don't think datashade with histogram equalization is appropriate for this data.

**Comment by chbrandt** [comment]
Cool, thanks @philippjfr , done. I could not set the colormap though. Any suggestion?

**Comment by philippjfr** [comment]
When rasterized the colormap is set as a style option using .opts(cmap=...)

**Comment by chbrandt** [comment]
@brendancol Branch [skyplot_colorbar](https://github.com/Quansight/lsst_dashboard/tree/skyplot_colorbar) has the skyplot with colorbar (viridis). It is using `rasterize` and `viridis`. It is _not_ using any _spreading_ though, to be solved.

**Comment by chbrandt** [comment]
@brendancol Fixed the datapoints spreading limitation when using colorbar in Skyplot in commit b6db1dc286271e654abb7082a9899a385c8a71c7 of branch `skyplot_colorbar`; not yet merged to master because there are some widgets in need for styling, but branch _is_ running stable.

The overall solution is to (go back and) use `datashade()` + `dynspread()`, and over it (like `decimate()`) we use a transparent `rasterize()`, to which we can associate a colorbar. The layers use the same colormap and aggregator.

Once we have the widgets therein decently styled we can merge to master and close here.

**Comment by chbrandt** [comment]
- [ ] use rasterize once, and _then_ `shade()` it (to have the `datashade()` result)

**Comment by kidpixo** [comment]
@chbrandt thanks for the hint!

I'm using something like:

```
import holoviews.operation.datashader as hds

raster = hds.raster(data).opts(alpha=1,colorbar=True)

raster*\
background_image\*
hds.shade(raster).opts(alpha=0.7)
```
because in my case I found the setting `alpha=0 ` to `raster` apply to the colorbar too.

This way `raster` is covered by the the `hds.shade(raster)` anyway, plus I have a background image.
